"use client";

import { Poppins, Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ScrollSmoother } from "gsap/ScrollSmoother";
import { useGSAP } from "@gsap/react";
import { useRef } from "react";

gsap.registerPlugin(useGSAP, ScrollTrigger, ScrollSmoother);

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Breezy Works | Freelance Agency",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const main = useRef<HTMLDivElement>(null);
  const smoother = useRef<ScrollSmoother>(null);

  useGSAP(
    () => {
      // create the smooth scroller FIRST!
      smoother.current = ScrollSmoother.create({
        smooth: 2, // seconds it takes to "catch up" to native scroll position
        effects: true, // look for data-speed and data-lag attributes on elements and animate accordingly
      });
      ScrollTrigger.create({
        trigger: ".box-c",
        pin: true,
        start: "center center",
        end: "+=300",
        markers: true,
      });
    },
    { scope: main }
  );

  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${poppins.variable} antialiased`}>
        <Header />
        <div id="smooth-wrapper" ref={main}>
          <div id="smooth-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
